integrate pearl street scraper
TappedOpenSource/webscrapers pull request #1
Opened 2024-03-02 05:29 UTC by Philip-Hart

2024-03-02 19:38 UTC, jonaylor89 commented on package.json
> +    "scrape:pearlstreet": "npm run build && node dist/scrapers/pearlstreet/scraper.js",
you're a legend for remembering to do this - good stuff

2024-03-02 19:40 UTC, jonaylor89 commented on src/scrapers/comet-old/scraper.ts
>      ticketPrice: null,
instead of `advTicketPrice` and `doorPrice` - let's just use `ticketPrice` and `doorPrice`.

And if we don't see a door price on the website then just say door price is ticket price

2024-03-02 19:41 UTC, jonaylor89 commented on src/scrapers/goldenpony/scraper.ts
> +    await browser.close();
don't close the browser because it's shared by all the events. close it when you're finished scraping everything

2024-03-02 19:41 UTC, jonaylor89 commented on src/scrapers/pearlstreet/config.ts
> +  location: {
how did you get this? if it took you a while, i can show you how to get the location faster

2024-03-02 19:43 UTC, jonaylor89 commented on src/scrapers/pearlstreet/parsing.ts
> +    These are mostly EDM musicians so things like B2B mean 'back to back' so that's not part of the name
change this prompt pearl street warehouse is not an EDM venue

2024-03-02 19:44 UTC, jonaylor89 commented on src/scrapers/pearlstreet/scraper.ts
> +  const priceContainer = await page.waitForSelector('.tw-price');
move this parsing code into a function and put it in `./parsing.ts`

2024-03-02 19:45 UTC, jonaylor89 requested changes
check out the comments i left

2024-03-05 02:23 UTC, Philip-Hart commented on package.json
> +    "scrape:pearlstreet": "npm run build && node dist/scrapers/pearlstreet/scraper.js",
Thanks, I just use these as a run script while testing

2024-03-05 02:25 UTC, Philip-Hart commented on src/scrapers/comet-old/scraper.ts
>      ticketPrice: null,
For golden pony and pearl street I find the pre-show online price and the door price. If there is no door price, the door price becomes the first captured ticketPrice, otherwise, the ticketPrice is the pre-show price.

2024-03-05 02:27 UTC, Philip-Hart commented on src/scrapers/pearlstreet/config.ts
> +  location: {
I definitely just used an online tool. would let me know how you get location?

2024-03-05 16:21 UTC, jonaylor89 approved these changes
LGTM

2024-03-05 16:21 UTC, merged